/* global __PRIVACY_MAGIC_INJECT__, __disabledSettings */

const reflectApply = (...args) => Reflect.apply(...args);

export const reflectApplySafe = (func, thisArg, args) => {
  try {
    return reflectApply(func, thisArg, args);
  } catch (error) {
    return undefined;
  }
};

export const objectDefinePropertiesSafe = Object.defineProperties;
const objectGetOwnPropertyDescriptorsSafe = Object.getOwnPropertyDescriptors;

export const redefinePropertiesSafe = (obj, propertyMap) => {
  const originalDescriptors = objectGetOwnPropertyDescriptorsSafe(obj);
  objectDefinePropertiesSafe(obj, propertyMap);
  return () => objectDefinePropertiesSafe(obj, originalDescriptors);
};

export const nonProperty = { get: undefined, set: undefined, configurable: true };

export const redefinePropertyValues = (obj, propertyMap) => {
  const originalProperties = {};
  const newProperties = {};
  for (const [prop, value] of Object.entries(propertyMap)) {
    const originalDescriptor = Object.getOwnPropertyDescriptor(obj, prop);
    originalProperties[prop] = originalDescriptor || nonProperty;
    if (value === undefined) {
      newProperties[prop] = nonProperty;
    } else {
      if (!originalDescriptor) {
        newProperties[prop] = { configurable: true, get: () => value };
      } else if (originalDescriptor.value) {
        newProperties[prop] = { ...originalDescriptor, value };
      } else {
        newProperties[prop] = { ...originalDescriptor, get: () => value };
      }
    }
  }
  Object.defineProperties(obj, newProperties);
  return () => {
    objectDefinePropertiesSafe(obj, originalProperties);
  };
};

export const createSafeMethod = (globalInterface, methodName) => {
  const originalMethod = Object.getOwnPropertyDescriptor(globalInterface.prototype, methodName).value;
  return (instance, ...args) => reflectApplySafe(originalMethod, instance, args);
};

const weakMapGet = Object.getOwnPropertyDescriptor(WeakMap.prototype, 'get').value;
const weakMapHas = Object.getOwnPropertyDescriptor(WeakMap.prototype, 'has').value;
const weakMapSet = Object.getOwnPropertyDescriptor(WeakMap.prototype, 'set').value;
export const weakMapGetSafe = (weakMap, key) => reflectApplySafe(weakMapGet, weakMap, [key]);
export const weakMapHasSafe = (weakMap, key) => reflectApplySafe(weakMapHas, weakMap, [key]);
export const weakMapSetSafe = (weakMap, key, value) => reflectApplySafe(weakMapSet, weakMap, [key, value]);

export const reflectConstructSafe = Reflect.construct;

// Cache the bundle for injection to avoid re-creating it on every call.
let bundleForInjection;

// Makes a code bundle for injection into a sandboxed iframe or worker. The bundle
// includes the shared secret, the patch decisions, and the __PRIVACY_MAGIC_INJECT__
// wrapper function, which was generated by the rollup intro and outro. (See /rollup.config.js).
export const makeBundleForInjection = (disabledSettings) => {
  if (!bundleForInjection) {
    bundleForInjection = `
  (function () {
    const __PRIVACY_MAGIC_INJECT__ = ${__PRIVACY_MAGIC_INJECT__.toString()};
    __PRIVACY_MAGIC_INJECT__(${JSON.stringify(disabledSettings)});
  })();
    `;
  }
  return bundleForInjection;
};

export const getDisabledSettings = (relevantSettings) => {
  if (__disabledSettings !== undefined && __disabledSettings.length > 0) {
    return __disabledSettings;
  }
  let result = [];
  try {
    document.cookie.split(';').forEach(cookie => {
      const [key, value] = cookie.trim().split('=');
      if (key === '__pm__disabled_settings') {
        result = value.split(',');
      }
    });
    document.cookie = '__pm__disabled_settings=; Secure; SameSite=None; Path=/; Partitioned; Expires=Thu, 01 Jan 1970 00:00:00 GMT';
    if (result.length === 1 && result[0] === '') {
      result = [];
    }
    if (relevantSettings) {
      result = result.filter(setting => relevantSettings.includes(setting));
    }
  } catch (error) {
    console.error('error getting disabled settings from cookie:', error);
  }
  // eslint-disable-next-line no-global-assign
  __disabledSettings = result;
  return result;
};
