import { ContentSettingId, CONTENT_SETTING_IDS, SETTING_COOKIE_PREFIX } from "@src/common/setting-ids"
import { GlobalScope } from "./globalObject"

export const spoofMediaQuery = (globalObject: GlobalScope, key: string, spoofValue: string, targetDefault = false): void => {
  const oldMatchMedia = globalObject.matchMedia.bind(globalObject)
  const targetRegex = new RegExp(`\\(\\s*${key}\\s*:\\s*${spoofValue}\\s*\\)`, 'ig')
  const nonTargetRegex = new RegExp(`\\(\\s*${key}\\s*:\\s*[^)]+\\s*\\)`, 'ig')
  const defaultRegex = new RegExp(`\\(\\s*${key}\\s*\\)`, 'ig')
  const defaultReplacement = targetDefault ? 'all' : 'not all'
  const spoof = (mediaQueryString: string): string =>
    mediaQueryString
      .replace(targetRegex, 'all')
      .replace(nonTargetRegex, 'not all')
      .replace(defaultRegex, defaultReplacement)
  globalObject.matchMedia = (mediaQueryString) => oldMatchMedia(spoof(mediaQueryString))
}


// Cache the bundle for injection to avoid re-creating it on every call.
let bundleForInjection: string | undefined

// Makes a code bundle for injection into a sandboxed iframe or a worker. The bundle
// includes the shared secret, the patch decisions, and the __PRIVACY_MAGIC_INJECT__
// wrapper function, which was generated by the esbuild banner and footer. (See /esbuild.config.js).
export const makeBundleForInjection = (disabledSettings: string[]): string => {
  if (bundleForInjection === undefined || bundleForInjection === '') {
    bundleForInjection = `
  (function () {
    const __PRIVACY_MAGIC_INJECT__ = ${__PRIVACY_MAGIC_INJECT__.toString()};
    __PRIVACY_MAGIC_INJECT__(${JSON.stringify(disabledSettings)});
  })();
    `
  }
  return bundleForInjection
}

// Expire a settings cookie. The extension sets its cookies as Partitioned, but a
// page or server can create a same-named cookie without Partitioned. That is a
// different cookie (the partition key is part of a cookie's identity), so clear both.
const clearSettingCookie = (key: string): void => {
  document.cookie = `${key}=; max-age=0; Secure; SameSite=None; Path=/; Partitioned`
  document.cookie = `${key}=; max-age=0; Secure; Path=/`
}

export const getDisabledSettings = (): ContentSettingId[] => {
  if (__disabledSettings !== undefined && Array.isArray(__disabledSettings)) {
    // __disabledSettings has been set by a parent frame or worker.
    return __disabledSettings
  }
  const result: ContentSettingId[] = []
  // Maybe gather disabled settings from the cookie.
  try {
    // We only honor DNR Set-Cookie on https: documents. blob:/data:/about:
    // documents can share a cookie jar with their creator, so honoring cookies
    // there would let a page forge disable flags and location.replace() to them.
    if (globalThis.location?.protocol === 'https:') {
      // The extension emits a "1" (enabled) or "0" (disabled) cookie for every setting
      // on every response. A page or server can plant lookalike cookies (for example an
      // unpartitioned twin of our Partitioned cookie), but to make a setting look
      // disabled it must do so while our own "1" is absent. So a setting counts as
      // disabled only if every cookie for it says "0"; a single "1" (or any other
      // value) vetoes it. Forgery can therefore only keep protection on, never turn it off.
      const allZero = Object.create(null) as Record<string, boolean>
      for (const cookie of document.cookie.split(';')) {
        const [key, value] = cookie.trim().split('=')
        if (key.startsWith(SETTING_COOKIE_PREFIX)) {
          clearSettingCookie(key)
          const settingId = key.slice(SETTING_COOKIE_PREFIX.length)
          allZero[settingId] = (allZero[settingId] === undefined || allZero[settingId]) && value === '0'
        }
      }
      for (const settingId of Object.keys(allZero)) {
        if (allZero[settingId] && (CONTENT_SETTING_IDS as readonly string[]).includes(settingId)) {
          result.push(settingId as ContentSettingId)
        }
      }
    }
  } catch (error) {
    console.error('error getting disabled settings from cookie:', error)
  }
  __disabledSettings = result
  return __disabledSettings
}

export type FetchID = string

export const objectGetEntriesSafe = <K extends string, V>(object: Partial<Record<K, V>>): [K, V][] => {
  return Object.entries(object) as [K, V][]
}