import { ContentSettingId } from "@src/common/setting-ids"

export const spoofMediaQuery = (key: string, spoofValue: string, targetDefault = false): void => {
  const oldMatchMedia = self.matchMedia
  const targetRegex = new RegExp(`\\(\\s*${key}\\s*:\\s*${spoofValue}\\s*\\)`, 'ig')
  const nonTargetRegex = new RegExp(`\\(\\s*${key}\\s*:\\s*[^)]+\\s*\\)`, 'ig')
  const defaultRegex = new RegExp(`\\(\\s*${key}\\s*\\)`, 'ig')
  const defaultReplacement = targetDefault ? 'all' : 'not all'
  const spoof = (mediaQueryString: string): string =>
    mediaQueryString
      .replace(targetRegex, 'all')
      .replace(nonTargetRegex, 'not all')
      .replace(defaultRegex, defaultReplacement)
  self.matchMedia = (mediaQueryString) => oldMatchMedia(spoof(mediaQueryString))
}


// Cache the bundle for injection to avoid re-creating it on every call.
let bundleForInjection: string | undefined

// Makes a code bundle for injection into a sandboxed iframe or a worker. The bundle
// includes the shared secret, the patch decisions, and the __PRIVACY_MAGIC_INJECT__
// wrapper function, which was generated by the esbuild banner and footer. (See /esbuild.config.js).
export const makeBundleForInjection = (disabledSettings: string[]): string => {
  if (bundleForInjection === undefined || bundleForInjection === '') {
    bundleForInjection = `
  (function () {
    const __PRIVACY_MAGIC_INJECT__ = ${__PRIVACY_MAGIC_INJECT__.toString()};
    __PRIVACY_MAGIC_INJECT__(${JSON.stringify(disabledSettings)});
  })();
    `
  }
  return bundleForInjection
}

export const getDisabledSettings = (relevantSettings?: ContentSettingId[]): ContentSettingId[] => {
  if (__disabledSettings !== undefined && Array.isArray(__disabledSettings)) {
    return __disabledSettings
  }
  let result: string[] = []
  try {
    document.cookie.split(';').forEach(cookie => {
      const [key, value] = cookie.trim().split('=')
      if (key === '__pm__disabled_settings' && value !== undefined) {
        result = value.split(',')
      }
    })
    document.cookie = '__pm__disabled_settings=; Secure; SameSite=None; Path=/; Partitioned; Expires=Thu, 01 Jan 1970 00:00:00 GMT'
    if (result.length === 1 && result[0] === '') {
      result = []
    }
    if (relevantSettings != null) {
      result = result.filter(setting => (relevantSettings as string[]).includes(setting))
    }
  } catch (error) {
    console.error('error getting disabled settings from cookie:', error)
  }

  __disabledSettings = result as ContentSettingId[]
  return __disabledSettings
}

export type FetchID = string
