import { ContentSettingId, CONTENT_SETTING_IDS } from "@src/common/setting-ids"
import { GlobalScope } from "./globalObject"

export const spoofMediaQuery = (globalObject: GlobalScope, key: string, spoofValue: string, targetDefault = false): void => {
  const oldMatchMedia = globalObject.matchMedia.bind(globalObject)
  const targetRegex = new RegExp(`\\(\\s*${key}\\s*:\\s*${spoofValue}\\s*\\)`, 'ig')
  const nonTargetRegex = new RegExp(`\\(\\s*${key}\\s*:\\s*[^)]+\\s*\\)`, 'ig')
  const defaultRegex = new RegExp(`\\(\\s*${key}\\s*\\)`, 'ig')
  const defaultReplacement = targetDefault ? 'all' : 'not all'
  const spoof = (mediaQueryString: string): string =>
    mediaQueryString
      .replace(targetRegex, 'all')
      .replace(nonTargetRegex, 'not all')
      .replace(defaultRegex, defaultReplacement)
  globalObject.matchMedia = (mediaQueryString) => oldMatchMedia(spoof(mediaQueryString))
}


// Cache the bundle for injection to avoid re-creating it on every call.
let bundleForInjection: string | undefined

// Makes a code bundle for injection into a sandboxed iframe or a worker. The bundle
// includes the shared secret, the patch decisions, and the __PRIVACY_MAGIC_INJECT__
// wrapper function, which was generated by the esbuild banner and footer. (See /esbuild.config.js).
export const makeBundleForInjection = (disabledSettings: string[]): string => {
  if (bundleForInjection === undefined || bundleForInjection === '') {
    bundleForInjection = `
  (function () {
    const __PRIVACY_MAGIC_INJECT__ = ${__PRIVACY_MAGIC_INJECT__.toString()};
    __PRIVACY_MAGIC_INJECT__(${JSON.stringify(disabledSettings)});
  })();
    `
  }
  return bundleForInjection
}

export const getDisabledSettings = (): ContentSettingId[] => {
  if (__disabledSettings !== undefined && Array.isArray(__disabledSettings)) {
    // __disabledSettings has been set by a parent frame or worker.
    return __disabledSettings
  }
  // Gather disabled settings from the cookie.
  const result: ContentSettingId[] = []
  try {
    const cookieItems = document.cookie.split(';')
    for (const cookie of cookieItems) {
      const [key, value] = cookie.trim().split('=')
      if (key.startsWith('__pm_setting__')) {
        // Clear the cookie.
        document.cookie = `${key}=; max-age=0; Secure; SameSite=None; Path=/; Partitioned`
        // Add the setting ID to the list of disabled settings if the value is '0'.
        if (value === '0') {
          const settingId = key.split('__pm_setting__')[1]
          if (settingId != null && (CONTENT_SETTING_IDS as readonly string[]).includes(settingId)) {
            result.push(settingId as ContentSettingId)
          }
        }
      }
    }
  } catch (error) {
    console.error('error getting disabled settings from cookie:', error)
  }
  __disabledSettings = result
  return __disabledSettings
}

export type FetchID = string

export const objectGetEntriesSafe = <K extends string, V>(object: Record<K, V>): [K, V][] => {
  return Object.entries(object) as [K, V][]
}