import { stringTrimSafe } from "@src/content_scripts/helpers/safe"
import { getOperatingSystem } from "@src/common/operating-system"

const makeLowerCaseSet = (fontNames: string[]): Set<string> =>
  new Set(fontNames.map(fontName => fontName.toLowerCase()))

/** List of fonts that are allowed on Windows.
 * Based on the list of fonts installed by default on Windows 11:
 * https://learn.microsoft.com/en-us/typography/fonts/windows_11_font_list
 */
const ALLOWED_FONTS_WINDOWS: Set<string> = makeLowerCaseSet([
  'Arial',
  'Arial Italic',
  'Arial Bold',
  'Arial Bold Italic',
  'Arial Black',
  'Bahnschrift',
  'Calibri Light',
  'Calibri Light Italic',
  'Calibri',
  'Calibri Italic',
  'Calibri Bold',
  'Calibri Bold Italic',
  'Cambria',
  'Cambria Italic',
  'Cambria Bold',
  'Cambria Bold Italic',
  'Cambria Math',
  'Candara Light',
  'Candara Light Italic',
  'Candara',
  'Candara Italic',
  'Candara Bold',
  'Candara Bold Italic',
  'Cascadia Code ExtraLight',
  'Cascadia Code ExtraLight Italic',
  'Cascadia Code Light',
  'Cascadia Code Light Italic',
  'Cascadia Code SemiLight',
  'Cascadia Code SemiLight Italic',
  'Cascadia Code Regular',
  'Cascadia Code Italic',
  'Cascadia Code SemiBold',
  'Cascadia Code SemiBold Italic',
  'Cascadia Code Bold',
  'Cascadia Code Bold Italic',
  'Cascadia Mono ExtraLight',
  'Cascadia Mono ExtraLight Italic',
  'Cascadia Mono Light',
  'Cascadia Mono Light Italic',
  'Cascadia Mono SemiLight',
  'Cascadia Mono SemiLight Italic',
  'Cascadia Mono Regular',
  'Cascadia Mono Italic',
  'Cascadia Mono SemiBold',
  'Cascadia Mono SemiBold Italic',
  'Cascadia Mono Bold',
  'Cascadia Mono Bold Italic',
  'Comic Sans MS',
  'Comic Sans MS Italic',
  'Comic Sans MS Bold',
  'Comic Sans MS Bold Italic',
  'Consolas',
  'Consolas Italic',
  'Consolas Bold',
  'Consolas Bold Italic',
  'Constantia',
  'Constantia Italic',
  'Constantia Bold',
  'Constantia Bold Italic',
  'Corbel Light',
  'Corbel Light Italic',
  'Corbel',
  'Corbel Italic',
  'Corbel Bold',
  'Corbel Bold Italic',
  'Courier New',
  'Courier New Italic',
  'Courier New Bold',
  'Courier New Bold Italic',
  'Ebrima',
  'Ebrima Bold',
  'Franklin Gothic Medium',
  'Franklin Gothic Medium Italic',
  'Gabriola',
  'Gadugi',
  'Gadugi Bold',
  'Georgia',
  'Georgia Italic',
  'Georgia Bold',
  'Georgia Bold Italic',
  'HoloLens MDL2 Assets',
  'Impact',
  'Ink Free',
  'Javanese Text',
  'Leelawadee UI',
  'Leelawadee UI Semilight',
  'Leelawadee UI Bold',
  'Lucida Console',
  'Lucida Sans Unicode',
  'Malgun Gothic',
  'Malgun Gothic Bold',
  'Malgun Gothic Semilight',
  'Marlett',
  'Microsoft Himalaya',
  'Microsoft JhengHei Light',
  'Microsoft JhengHei',
  'Microsoft JhengHei Bold',
  'Microsoft JhengHei UI Light',
  'Microsoft JhengHei UI',
  'Microsoft JhengHei UI Bold',
  'Microsoft New Tai Lue',
  'Microsoft New Tai Lue Bold',
  'Microsoft PhagsPa',
  'Microsoft PhagsPa Bold',
  'Microsoft Sans Serif',
  'Microsoft Tai Le',
  'Microsoft Tai Le Bold',
  'Microsoft YaHei Light',
  'Microsoft YaHei',
  'Microsoft YaHei Bold',
  'Microsoft YaHei UI Light',
  'Microsoft YaHei UI',
  'Microsoft YaHei UI Bold',
  'Microsoft Yi Baiti',
  'MingLiU-ExtB',
  'PMingLiU-ExtB',
  'MingLiU_HKSCS-ExtB',
  'Mongolian Baiti',
  'MS Gothic',
  'MS PGothic',
  'MS UI Gothic',
  'MV Boli',
  'Myanmar Text',
  'Myanmar Text Bold',
  'Nirmala UI Semilight',
  'Nirmala UI',
  'Nirmala UI Bold',
  'Palatino Linotype',
  'Palatino Linotype Italic',
  'Palatino Linotype Bold',
  'Palatino Linotype Bold Italic',
  'Segoe Fluent Icons',
  'Segoe MDL2 Assets',
  'Segoe Print',
  'Segoe Print Bold',
  'Segoe Script',
  'Segoe Script Bold',
  'Segoe UI Light',
  'Segoe UI Light Italic',
  'Segoe UI Semilight',
  'Segoe UI Semilight Italic',
  'Segoe UI',
  'Segoe UI Italic',
  'Segoe UI Semibold',
  'Segoe UI Semibold Italic',
  'Segoe UI Bold',
  'Segoe UI Bold Italic',
  'Segoe UI Black',
  'Segoe UI Black Italic',
  'Segoe UI Emoji',
  'Segoe UI Historic',
  'Segoe UI Symbol',
  'Segoe UI Variable Display Light',
  'Segoe UI Variable Display Semilight',
  'Segoe UI Variable Display Regular',
  'Segoe UI Variable Display Semibold',
  'Segoe UI Variable Display Bold',
  'Segoe UI Variable Small Light',
  'Segoe UI Variable Small Semilight',
  'Segoe UI Variable Small Regular',
  'Segoe UI Variable Small Semibold',
  'Segoe UI Variable Small Bold',
  'Segoe UI Variable Text Light',
  'Segoe UI Variable Text Semilight',
  'Segoe UI Variable Text Regular',
  'Segoe UI Variable Text Semibold',
  'Segoe UI Variable Text Bold',
  'SimSun',
  'NSimSun',
  'SimSun-ExtB',
  'Sitka Banner',
  'Sitka Banner Italic',
  'Sitka Banner Semibold',
  'Sitka Banner Semibold Italic',
  'Sitka Banner Bold',
  'Sitka Banner Bold Italic',
  'Sitka Display',
  'Sitka Display Italic',
  'Sitka Display Semibold',
  'Sitka Display Semibold Italic',
  'Sitka Display Bold',
  'Sitka Display Bold Italic',
  'Sitka Small',
  'Sitka Small Italic',
  'Sitka Small Semibold',
  'Sitka Small Semibold Italic',
  'Sitka Small Bold',
  'Sitka Small Bold Italic',
  'Sitka Heading',
  'Sitka Heading Italic',
  'Sitka Heading Semibold',
  'Sitka Heading Semibold Italic',
  'Sitka Heading Bold',
  'Sitka Heading Bold Italic',
  'Sitka Subheading',
  'Sitka Subheading Italic',
  'Sitka Subheading Semibold',
  'Sitka Subheading Semibold Italic',
  'Sitka Subheading Bold',
  'Sitka Subheading Bold Italic',
  'Sitka Text',
  'Sitka Text Italic',
  'Sitka Text Semibold',
  'Sitka Text Semibold Italic',
  'Sitka Text Bold',
  'Sitka Text Bold Italic',
  'Sylfaen',
  'Symbol',
  'Tahoma',
  'Tahoma Bold',
  'Times New Roman',
  'Times New Roman Italic',
  'Times New Roman Bold',
  'Times New Roman Bold Italic',
  'Trebuchet MS',
  'Trebuchet MS Italic',
  'Trebuchet MS Bold',
  'Trebuchet MS Bold Italic',
  'Verdana',
  'Verdana Italic',
  'Verdana Bold',
  'Verdana Bold Italic',
  'Webdings',
  'Wingdings',
  'Yu Gothic Light',
  'Yu Gothic Regular',
  'Yu Gothic Medium',
  'Yu Gothic Bold',
  'Yu Gothic UI Light',
  'Yu Gothic UI Semilight',
  'Yu Gothic UI Regular',
  'Yu Gothic UI Semibold',
  'Yu Gothic UI Bold',
])

/** List of fonts that are allowed on macOS.
 * Based on the list of fonts installed by default on macOS 26.0.1,
 * measured on 2026-02-18.
 */
const ALLOWED_FONTS_MACOS: Set<string> = makeLowerCaseSet([
  'Academy Engraved LET Plain:1.0',
  'Al Bayan Plain',
  'Al Bayan Bold',
  'Al Nile',
  'Al Nile Bold',
  'Al Tarikh Regular',
  'American Typewriter',
  'American Typewriter Bold',
  'American Typewriter Condensed',
  'American Typewriter Condensed Bold',
  'American Typewriter Condensed Light',
  'American Typewriter Light',
  'American Typewriter Semibold',
  'Andale Mono',
  'Apple Chancery',
  'Apple Braille',
  'Apple Braille Outline 6 Dot',
  'Apple Braille Outline 8 Dot',
  'Apple Braille Pinpoint 6 Dot',
  'Apple Braille Pinpoint 8 Dot',
  'Apple Color Emoji',
  'AppleGothic Regular',
  'AppleMyungjo Regular',
  'Apple SD Gothic Neo Bold',
  'Apple SD Gothic Neo ExtraBold',
  'Apple SD Gothic Neo Heavy',
  'Apple SD Gothic Neo Light',
  'Apple SD Gothic Neo Medium',
  'Apple SD Gothic Neo Regular',
  'Apple SD Gothic Neo SemiBold',
  'Apple SD Gothic Neo Thin',
  'Apple SD Gothic Neo UltraLight',
  'Apple Symbols',
  'Arial Black',
  'Arial Bold Italic',
  'Arial Bold',
  'Arial Italic',
  'Arial Hebrew',
  'Arial Hebrew Bold',
  'Arial Hebrew Light',
  'Arial Hebrew Scholar',
  'Arial Hebrew Scholar Bold',
  'Arial Hebrew Scholar Light',
  'Arial',
  'Arial Narrow',
  'Arial Narrow Bold',
  'Arial Narrow Bold Italic',
  'Arial Narrow Italic',
  'Arial Rounded MT Bold',
  'Arial Unicode MS',
  'Avenir Black',
  'Avenir Black Oblique',
  'Avenir Book',
  'Avenir Book Oblique',
  'Avenir Heavy',
  'Avenir Heavy Oblique',
  'Avenir Light',
  'Avenir Light Oblique',
  'Avenir Medium',
  'Avenir Medium Oblique',
  'Avenir Oblique',
  'Avenir Roman',
  'Avenir Next Bold',
  'Avenir Next Bold Italic',
  'Avenir Next Demi Bold',
  'Avenir Next Demi Bold Italic',
  'Avenir Next Heavy',
  'Avenir Next Heavy Italic',
  'Avenir Next Italic',
  'Avenir Next Medium',
  'Avenir Next Medium Italic',
  'Avenir Next Regular',
  'Avenir Next Ultra Light',
  'Avenir Next Ultra Light Italic',
  'Avenir Next Condensed Bold',
  'Avenir Next Condensed Bold Italic',
  'Avenir Next Condensed Demi Bold',
  'Avenir Next Condensed Demi Bold Italic',
  'Avenir Next Condensed Heavy',
  'Avenir Next Condensed Heavy Italic',
  'Avenir Next Condensed Italic',
  'Avenir Next Condensed Medium',
  'Avenir Next Condensed Medium Italic',
  'Avenir Next Condensed Regular',
  'Avenir Next Condensed Ultra Light',
  'Avenir Next Condensed Ultra Light Italic',
  'Ayuthaya',
  'Baghdad Regular',
  'Bangla MN',
  'Bangla MN Bold',
  'Bangla Sangam MN',
  'Bangla Sangam MN Bold',
  'Baskerville',
  'Baskerville Bold',
  'Baskerville Bold Italic',
  'Baskerville Italic',
  'Baskerville SemiBold',
  'Baskerville SemiBold Italic',
  'Beirut Regular',
  'Big Caslon Medium',
  'Bodoni Ornaments',
  'Bodoni 72 Bold',
  'Bodoni 72 Book',
  'Bodoni 72 Book Italic',
  'Bodoni 72 Oldstyle Bold',
  'Bodoni 72 Oldstyle Book',
  'Bodoni 72 Oldstyle Book Italic',
  'Bodoni 72 Smallcaps Book',
  'Bradley Hand Bold',
  'Brush Script MT Italic',
  'Chalkboard',
  'Chalkboard Bold',
  'Chalkboard SE Bold',
  'Chalkboard SE Light',
  'Chalkboard SE Regular',
  'Chalkduster',
  'Charter Black',
  'Charter Black Italic',
  'Charter Bold',
  'Charter Bold Italic',
  'Charter Italic',
  'Charter Roman',
  'Cochin',
  'Cochin Bold',
  'Cochin Bold Italic',
  'Cochin Italic',
  'Comic Sans MS',
  'Comic Sans MS Bold',
  'Copperplate',
  'Copperplate Bold',
  'Copperplate Light',
  'Corsiva Hebrew',
  'Corsiva Hebrew Bold',
  'Courier New Bold Italic',
  'Courier New Bold',
  'Courier New Italic',
  'Courier New',
  'DIN Alternate Bold',
  'DIN Condensed Bold',
  'Damascus Regular',
  'Damascus Bold',
  'Damascus Light',
  'Damascus Medium',
  'Damascus Semi Bold',
  'DecoType Naskh Regular',
  'Devanagari MT',
  'Devanagari MT Bold',
  'Devanagari Sangam MN',
  'Devanagari Sangam MN Bold',
  'Didot',
  'Didot Bold',
  'Didot Italic',
  'Diwan Kufi Regular',
  'Mishafi Regular',
  'Mishafi Gold Regular',
  'Diwan Thuluth Regular',
  'Euphemia UCAS',
  'Euphemia UCAS Bold',
  'Euphemia UCAS Italic',
  'Farah Regular',
  'Farisi Regular',
  'Futura Bold',
  'Futura Condensed ExtraBold',
  'Futura Condensed Medium',
  'Futura Medium',
  'Futura Medium Italic',
  'GB18030 Bitmap',
  'Galvji',
  'Galvji Bold',
  'Galvji Bold Oblique',
  'Galvji Oblique',
  'Geeza Pro Regular',
  'Geeza Pro Bold',
  'Geneva',
  'Georgia',
  'Georgia Bold',
  'Georgia Bold Italic',
  'Georgia Italic',
  'Gill Sans',
  'Gill Sans Bold',
  'Gill Sans Bold Italic',
  'Gill Sans Italic',
  'Gill Sans Light',
  'Gill Sans Light Italic',
  'Gill Sans SemiBold',
  'Gill Sans SemiBold Italic',
  'Gill Sans UltraBold',
  'Grantha Sangam MN Bold',
  'Grantha Sangam MN Regular',
  'Gujarati MT',
  'Gujarati MT Bold',
  'Gujarati Sangam MN',
  'Gujarati Sangam MN Bold',
  'Gurmukhi MN',
  'Gurmukhi MN Bold',
  'Gurmukhi Sangam MN',
  'Gurmukhi Sangam MN Bold',
  'Helvetica',
  'Helvetica Bold',
  'Helvetica Bold Oblique',
  'Helvetica Light',
  'Helvetica Light Oblique',
  'Helvetica Oblique',
  'Helvetica Neue',
  'Helvetica Neue Bold',
  'Helvetica Neue Bold Italic',
  'Helvetica Neue Condensed Black',
  'Helvetica Neue Condensed Bold',
  'Helvetica Neue Italic',
  'Helvetica Neue Light',
  'Helvetica Neue Light Italic',
  'Helvetica Neue Medium',
  'Helvetica Neue Medium Italic',
  'Helvetica Neue Thin',
  'Helvetica Neue Thin Italic',
  'Helvetica Neue UltraLight',
  'Helvetica Neue UltraLight Italic',
  'Herculanum',
  'Hiragino Maru Gothic ProN W4',
  'Hiragino Mincho ProN W3',
  'Hiragino Mincho ProN W6',
  'Hiragino Sans W0',
  'Hiragino Sans W1',
  'Hiragino Sans W2',
  'Hiragino Sans W3',
  'Hiragino Sans W4',
  'Hiragino Sans W5',
  'Hiragino Sans W6',
  'Hiragino Sans W7',
  'Hiragino Sans W8',
  'Hiragino Sans W9',
  'Hiragino Sans GB W3',
  'Hiragino Sans GB W6',
  'Hoefler Text Black',
  'Hoefler Text Black Italic',
  'Hoefler Text Italic',
  'Hoefler Text Ornaments',
  'Hoefler Text',
  'ITF Devanagari Bold',
  'ITF Devanagari Book',
  'ITF Devanagari Demi',
  'ITF Devanagari Light',
  'ITF Devanagari Medium',
  'ITF Devanagari Marathi Bold',
  'ITF Devanagari Marathi Book',
  'ITF Devanagari Marathi Demi',
  'ITF Devanagari Marathi Light',
  'ITF Devanagari Marathi Medium',
  'Impact',
  'InaiMathi',
  'InaiMathi Bold',
  'Kailasa Regular',
  'Kailasa Bold',
  'Kannada MN',
  'Kannada MN Bold',
  'Kannada Sangam MN',
  'Kannada Sangam MN Bold',
  'Kefa III Regular Bold',
  'Kefa III Regular ExtraBold',
  'Kefa III Regular Light',
  'Kefa III Regular Regular',
  'Khmer MN',
  'Khmer MN Bold',
  'Khmer Sangam MN',
  'Kohinoor Bangla Bold',
  'Kohinoor Bangla Light',
  'Kohinoor Bangla Medium',
  'Kohinoor Bangla',
  'Kohinoor Bangla Semibold',
  'Kohinoor Devanagari Bold',
  'Kohinoor Devanagari Light',
  'Kohinoor Devanagari Medium',
  'Kohinoor Devanagari Regular',
  'Kohinoor Devanagari Semibold',
  'Kohinoor Gujarati Bold',
  'Kohinoor Gujarati Light',
  'Kohinoor Gujarati Medium',
  'Kohinoor Gujarati Regular',
  'Kohinoor Gujarati Semibold',
  'Kohinoor Telugu Bold',
  'Kohinoor Telugu Light',
  'Kohinoor Telugu Medium',
  'Kohinoor Telugu',
  'Kohinoor Telugu Semibold',
  'Kokonor Regular',
  'Krungthep',
  'KufiStandardGK Regular',
  'Lao MN',
  'Lao MN Bold',
  'Lao Sangam MN',
  'Lucida Grande',
  'Lucida Grande Bold',
  'Luminari',
  'Malayalam MN',
  'Malayalam MN Bold',
  'Malayalam Sangam MN',
  'Malayalam Sangam MN Bold',
  'Marker Felt Thin',
  'Marker Felt Wide',
  'Menlo Bold',
  'Menlo Bold Italic',
  'Menlo Italic',
  'Menlo Regular',
  'Microsoft Sans Serif',
  'Monaco',
  'Monoton',
  'Gurmukhi MT',
  'Mshtakan',
  'Mshtakan Bold',
  'Mshtakan BoldOblique',
  'Mshtakan Oblique',
  'MuktaMahee Bold',
  'MuktaMahee ExtraBold',
  'MuktaMahee ExtraLight',
  'MuktaMahee Light',
  'MuktaMahee Medium',
  'MuktaMahee Regular',
  'MuktaMahee SemiBold',
  'Muna Regular',
  'Muna Black',
  'Muna Bold',
  'Myanmar MN',
  'Myanmar MN Bold',
  'Myanmar Sangam MN',
  'Myanmar Sangam MN Bold',
  'Nadeem Regular',
  'New Peninim MT',
  'New Peninim MT Bold',
  'New Peninim MT Bold Inclined',
  'New Peninim MT Inclined',
  'Noteworthy Bold',
  'Noteworthy Light',
  'Noto Nastaliq Urdu',
  'Noto Nastaliq Urdu Bold',
  'Noto Sans Batak Regular',
  'Noto Sans Kannada Black',
  'Noto Sans Kannada Bold',
  'Noto Sans Kannada ExtraBold',
  'Noto Sans Kannada ExtraLight',
  'Noto Sans Kannada Light',
  'Noto Sans Kannada Medium',
  'Noto Sans Kannada Regular',
  'Noto Sans Kannada SemiBold',
  'Noto Sans Kannada Thin',
  'Noto Sans Myanmar Black',
  'Noto Sans Myanmar Bold',
  'Noto Sans Myanmar ExtraBold',
  'Noto Sans Myanmar ExtraLight',
  'Noto Sans Myanmar Light',
  'Noto Sans Myanmar Medium',
  'Noto Sans Myanmar Regular',
  'Noto Sans Myanmar SemiBold',
  'Noto Sans Myanmar Thin',
  'Noto Sans NKo Regular',
  'Noto Sans Oriya',
  'Noto Sans Oriya Bold',
  'Noto Sans Syriac Regular Regular',
  'Noto Sans Syriac Regular Black',
  'Noto Sans Syriac Regular Bold',
  'Noto Sans Syriac Regular ExtraBold',
  'Noto Sans Syriac Regular ExtraLight',
  'Noto Sans Syriac Regular Light',
  'Noto Sans Syriac Regular Medium',
  'Noto Sans Syriac Regular SemiBold',
  'Noto Sans Syriac Regular Thin',
  'Noto Sans Tagalog Regular',
  'Noto Serif Myanmar Black',
  'Noto Serif Myanmar Bold',
  'Noto Serif Myanmar ExtraBold',
  'Noto Serif Myanmar ExtraLight',
  'Noto Serif Myanmar Light',
  'Noto Serif Myanmar Medium',
  'Noto Serif Myanmar Regular',
  'Noto Serif Myanmar SemiBold',
  'Noto Serif Myanmar Thin',
  'Optima Bold',
  'Optima Bold Italic',
  'Optima ExtraBlack',
  'Optima Italic',
  'Optima Regular',
  'Oriya MN',
  'Oriya MN Bold',
  'Oriya Sangam MN',
  'Oriya Sangam MN Bold',
  'PT Mono Bold',
  'PT Mono',
  'PT Sans Bold',
  'PT Sans Bold Italic',
  'PT Sans Caption',
  'PT Sans Caption Bold',
  'PT Sans Italic',
  'PT Sans Narrow',
  'PT Sans Narrow Bold',
  'PT Sans',
  'PT Serif Bold',
  'PT Serif Bold Italic',
  'PT Serif Caption',
  'PT Serif Caption Italic',
  'PT Serif Italic',
  'PT Serif',
  'Palatino Bold',
  'Palatino Bold Italic',
  'Palatino Italic',
  'Palatino',
  'Papyrus',
  'Papyrus Condensed',
  'Party LET Plain',
  'Phosphate Inline',
  'Phosphate Solid',
  'PingFang HK Light',
  'PingFang HK Medium',
  'PingFang HK Regular',
  'PingFang HK Semibold',
  'PingFang HK Thin',
  'PingFang HK Ultralight',
  'PingFang MO Light',
  'PingFang MO Medium',
  'PingFang MO Regular',
  'PingFang MO Semibold',
  'PingFang MO Thin',
  'PingFang MO Ultralight',
  'PingFang SC Light',
  'PingFang SC Medium',
  'PingFang SC Regular',
  'PingFang SC Semibold',
  'PingFang SC Thin',
  'PingFang SC Ultralight',
  'PingFang TC Light',
  'PingFang TC Medium',
  'PingFang TC Regular',
  'PingFang TC Semibold',
  'PingFang TC Thin',
  'PingFang TC Ultralight',
  'Plantagenet Cherokee',
  'Raanana',
  'Raanana Bold',
  'Rockwell Bold',
  'Rockwell Bold Italic',
  'Rockwell Italic',
  'Rockwell',
  'Heiti SC Light',
  'Heiti SC Medium',
  'Heiti TC Light',
  'Heiti TC Medium',
  'STIX Two Math Regular',
  'STIX Two Text Regular',
  'STIX Two Text Italic Italic',
  'STIX Two Text Italic Bold Italic',
  'STIX Two Text Italic Medium Italic',
  'STIX Two Text Italic SemiBold Italic',
  'STIX Two Text Bold',
  'STIX Two Text Medium',
  'STIX Two Text SemiBold',
  'STSong',
  'Songti SC Black',
  'Songti SC Bold',
  'Songti SC Light',
  'Songti SC Regular',
  'Songti TC Bold',
  'Songti TC Light',
  'Songti TC Regular',
  'Sana Regular',
  'Sathu',
  'Savoye LET Plain:1.0',
  'Shree Devanagari 714',
  'Shree Devanagari 714 Bold',
  'Shree Devanagari 714 Bold Italic',
  'Shree Devanagari 714 Italic',
  'SignPainter-HouseScript',
  'SignPainter-HouseScript Semibold',
  'Silom',
  'Sinhala MN',
  'Sinhala MN Bold',
  'Sinhala Sangam MN',
  'Sinhala Sangam MN Bold',
  'Skia Regular',
  'Skia Black',
  'Skia Black Condensed',
  'Skia Black Extended',
  'Skia Bold',
  'Skia Condensed',
  'Skia Extended',
  'Skia Light',
  'Skia Light Condensed',
  'Skia Light Extended',
  'Snell Roundhand',
  'Snell Roundhand Black',
  'Snell Roundhand Bold',
  'Sukhumvit Set Bold',
  'Sukhumvit Set Light',
  'Sukhumvit Set Medium',
  'Sukhumvit Set Semi Bold',
  'Sukhumvit Set Text',
  'Sukhumvit Set Thin',
  'Symbol',
  'Tahoma',
  'Tahoma Bold',
  'Tamil MN',
  'Tamil MN Bold',
  'Tamil Sangam MN',
  'Tamil Sangam MN Bold',
  'Telugu MN',
  'Telugu MN Bold',
  'Telugu Sangam MN',
  'Telugu Sangam MN Bold',
  'Thonburi',
  'Thonburi Bold',
  'Thonburi Light',
  'Times New Roman Bold Italic',
  'Times New Roman Bold',
  'Times New Roman Italic',
  'Times New Roman',
  'Trattatello',
  'Trebuchet MS Bold Italic',
  'Trebuchet MS',
  'Trebuchet MS Bold',
  'Trebuchet MS Italic',
  'Verdana',
  'Verdana Bold',
  'Verdana Bold Italic',
  'Verdana Italic',
  'Waseem Regular',
  'Waseem Light',
  'Webdings',
  'Wingdings',
  'Wingdings 2',
  'Wingdings 3',
  'Zapf Dingbats',
  'Zapfino'
])

export const isAllowedFont = (fontName: string): boolean => {
  const normalizedFontName = stringTrimSafe(fontName).toLowerCase()
  const os = getOperatingSystem()
  if (os === 'Windows') {
    return ALLOWED_FONTS_WINDOWS.has(normalizedFontName)
  } else if (os === 'macOS') {
    return ALLOWED_FONTS_MACOS.has(normalizedFontName)
  } else {
    return true // Allow all fonts on other operating systems
  }
}